### PR TITLE
Handle Delete, Home, End Keys

### PR DESCRIPTION
**Pull request by pegvin**
This PR implements <kbd>Delete</kbd>, <kbd>Home</kbd>, <kbd>End</kbd> Key presses on a `Input` element.

Solves The Issue #34

### CODE REVIEW

**Comment by felipemanga** [comment]
Are you still going to add support for Home/End to this PR?

**Comment by pegvin** [comment]
yea i will add home/end too

**Comment by pegvin** [comment]
pushed the changes! i've tested it works great!

**Comment by pegvin** [comment]
just a sec, don't merge, need to make the offset thing more generic.

**Comment by pegvin** [comment]
Okay, Done!!!

**Pull request merged**
